apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bjha1d26t-go
  janus-idp.io/tekton: bjha1d26t-go
  backstage.io/kubernetes-id: bjha1d26t-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bjha1d26t-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
