apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bjha1d26t-go-gitops
  description: This is GitOps manifest for bjha1d26t-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=bjha1d26t-go
    backstage.io/kubernetes-id: bjha1d26t-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bjha1d26t-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bjha1d26t-go
